version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    depends_on:
      - frontend


  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"