# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /my-app

# Copy the frontend files and folders from the project directory
COPY my-app/. .

# Copy package.json and package-lock.json (if available) to the container
COPY my-app/package*.json ./

# Install application dependencies
RUN npm install
RUN npm install -g serve

# Build React
RUN npm run build

# Expose the port your application will run on (if needed)
EXPOSE 3000

# Command to start your Node.js application
CMD [ "serve", "-s", "build", "-l", "3000" ]
